### ISSUE TITLE
Make a html page for user does not exist

### ISSUE THREAD

**Issue by shawshankkumar** [srm-kzilla/zeus-backend#44]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/74819565/190554347-845c11f7-64d1-4133-b9c8-5792cd48527e.png">

**Comment by prakhartiwari0** [comment]
May I work on this issue?

**Comment by Kevin-Aaaquil** [comment]
> May I work on this issue?

Sure, just go ahead and make a PR and we will review it

**Comment by Igdtuwresource** [comment]
![image](https://user-images.githubusercontent.com/112039921/194768706-95fca2d6-779d-4f76-ad2e-150f0e1f07c9.png)
@Kevin-Aaaquil I just need to add the html file in this repo for(user doesn't exist)__?

**Comment by Kevin-Aaaquil** [comment]
Yeah, just see the templates folder, just go ahead and add the html there, you can get a sense of the color schema from the other html pages

**Comment by shawshankkumar** [comment]
@Igdtuwresource Are you working on this?

**Comment by Igdtuwresource** [comment]
yes.
It will be finished by tommorow

**Comment by Igdtuwresource** [comment]
@Kevin-Aaaquil  I just have a doubt.
I need to make the page where you can show that user does not exist?
or you need html code on the website?

**Comment by Igdtuwresource** [comment]
@Kevin-Aaaquil kindly check the pull request and please do the nedful.
